fix: Handle ProvisionedThroughputExceededException throttling
vmware/vmware-go-kcl-v2 pull request #19
Opened 2023-01-23 20:02 UTC by spentakota

Signed-off-by: Shiva Pentakota <spentakota@vmware.com>

2023-01-23 21:25 UTC, Devika-Shanbhag commented on clientlibrary/config/config.go
> +		// MaxRetryCount The number of retries for getRecords in error case
Nit: Since this exportable field is in a general config file for the client library, we could have a comment like
`// MaxRetryCount The maximum number of retries in case of error` ?

That way it could be a general config field not necessarily only linked to getRecords()

2023-01-23 21:33 UTC, Devika-Shanbhag commented on clientlibrary/worker/polling-shard-consumer.go
> +		if transactionNum == 6 {
Could we make this magic number 6 a constant like `MaxReadTransactionsPerSecond`?

The condition then could be `if transactionNum > MaxReadTransactionsPerSecond`

2023-01-23 21:43 UTC, Devika-Shanbhag commented on clientlibrary/worker/polling-shard-consumer.go
> +				waitTime := time.Since(getRecordsTransactionTime)
There's scope to refactor this block (line 176-179) into a method - something like `waitASecond(waitTimePassed)`
Then reuse it in multiple places where we need to waitASecond()

2023-01-23 23:13 UTC, Devika-Shanbhag requested changes
Thanks for a quick yet comprehensive fix to handle `ProvisionedThroughputExceededException` throttling to getRecords()!

Overall, looks good to me with few review comments on lines and below over-arching suggestions which could be skipped or addressed later if not now:

1. From code quality perspective, getRecords() is becoming a brain overload - it might help to break it down into smaller logical methods that preferably - do one thing, do it well, do it only.
2. This method should be tested so we can assert that it is doing what we expect it to do - which is more important given its complex logic and calculations owing to underlying behaviors that you've rightly linked in comments. A quick basic test would really help in building confidence for these changes.

2023-01-23 23:13 UTC, Devika-Shanbhag commented on clientlibrary/worker/polling-shard-consumer.go
> +			remBytes = remBytes - float64(numBytes)
Nit: Noticed multiple occurrences of casting `numBytes` as `float64(numBytes)`. Would it make sense for `numBytes` to have float64 type to begin with? We might only need one casting on line 209 as 
`numBytes += float64(len(record.Data))`

Another instance for replacement with `-=`.

2023-01-24 00:40 UTC, Devika-Shanbhag commented on clientlibrary/worker/polling-shard-consumer.go
> +func (sc *PollingShardConsumer) callGetRecordsAPI(successfulTransactionNum *int, remBytes *float64,
Refactor suggestion: If all these fields are related or represent a particular struct, you could capture these fields in that struct or in the method's receiver struct (PollingShardConsumer).

You could return the values instead of updating the field references in this method - making callGetRecordsAPI() idempotent, such that it does not modify the fields that are being passed to it as parameters, but instead returns their values - that might clean this up from having multiple pointers.

2023-01-24 20:53 UTC, spentakota commented
Closing MR in favor of: https://github.com/vmware/vmware-go-kcl-v2/pull/21

2023-01-24 20:54 UTC, closed without merging